### ISSUE TITLE
Reorganize "Rest API" and "Val Town SDK" sections

### ISSUE THREAD

**Issue by stevekrouse** [val-town/val-town-docs#185]
The Rest API section is a bit stale, and I think the Val Town SDK belongs under there somehow

**Comment by Muhammad-Owais-Warsi** [comment]
Maybe we could include 'Val's SDK' under the 'REST API' section. Would really love to work on this improvement.

**Comment by stevekrouse** [comment]
Closed by https://github.com/val-town/val-town-docs/pull/235
