### ISSUE TITLE
Buttons cover up code snippets when using touch

### ISSUE THREAD

**Issue by TodePond** [val-town/val-town-docs#67]
Normally these buttons in the top right of a code snippet only appear when you hover the snippet.

But when you're using touch, they're always there. This is fine when your screen is big. But when you're using a small screen, it covers up the snippet, and you can't hide it:

<img width="318" alt="image" src="https://github.com/val-town/val-town-docs/assets/15892272/5dd32d5b-a009-4589-bd0a-1e2b0b30a468">

Not sure what the solution should be here. I notice that gitbook and docusaurus both only show this top-right button when you tap the snippet. That doesn't feel ideal either, but maybe better than having it cover up the snippet?

**Comment by stevekrouse** [comment]
Great feedback! This makes these snippets fairly ugly on mobile. Options:

1. We could make all our embeds look like the ones with file names because that adds a top row which solves this problem
2. We could copy "own row" styling but only for mobile

I don't love giving vals file names because they have val names, not file names, but I guess it's fine.

@Xkonti what do you think?

**Comment by Xkonti** [comment]
I think the option 1 is doable although initially we tried to avoid it (you can't get the title row to show up without specifying the title). The thing it that even though we would move the "Run in Val Town" button, the "copy" button would still be there in the top right corner.

**Comment by Xkonti** [comment]
Adding the CSS to simply add margin to the top of to code in code blocks in mobile sizing would be probably the easiest solution.

**Comment by stevekrouse** [comment]
> Adding the CSS to simply add margin to the top of to code in code blocks in mobile sizing would be probably the easiest solution.

Cool let's try this - send me a screenshot of how it'd look?

**Comment by Xkonti** [comment]
@stevekrouse Doesn't look *the best*, but it's really easy to implement.

![Image](https://github.com/val-town/val-town-docs/assets/5722272/fa5236e9-09b2-4e17-927f-0b10fee8b872)

And for code blocks that are not vals it looks like this:

![Image](https://github.com/val-town/val-town-docs/assets/5722272/592afe4a-af31-4b77-8904-cef6f90798da)

**Comment by stevekrouse** [comment]
Yeah not terrible, especially if it's only shown like that on moblie. Maybe go with that as a stop gap for now?

Random other idea: maybe if we just drop the extension (`.ts` or `.tsx`) from the val name in the header, we could switch all the examples to look like vals with names. It was the extension part that annoyed me because vals don't have those.

**Comment by Xkonti** [comment]
If you add titles through the dedicated syntax the can be anything.

Comment syntax:
````
```ts val
//resizeImage.ts
export ...
````

Dedicated syntax (preferred):
````
```ts title="resizeImage"
export ...
````

````
```ts title="@user/resizeImage usage example"
let img = ...
````

**Comment by stevekrouse** [comment]
Ok cool, so what do you think - update all vals to have titles or do the css trick?

**Comment by Xkonti** [comment]
I would lean towards all Vals having titles. Gives consistency, every Val having clear "run in Val Town" button. An approach seen often in various docs.

**Comment by stevekrouse** [comment]
Ok cool, can you make me an example of how it'd look? I could get on board with that.

Can we link from the val's `@stevekrouse/foo` title to that val?

Or maybe we should just drop the handle and have it just say `foo` for simplicity

**Comment by Xkonti** [comment]
## Docs-only code

The same preact val with a title:

![Image](https://github.com/val-town/val-town-docs/assets/5722272/d989a00c-f2f1-47ed-be19-d3bcdeee6757)

The copy button still obstructs code initially but the built-in code frame makes extra room for it when scrolled to the right:

![Image](https://github.com/val-town/val-town-docs/assets/5722272/12f900e4-8c59-482e-b6a3-0a5b576c7e86)

## Existing vals

Do you mean that the title `@stevekrouse/foo` would also be a link to an existing val? For that we have an embed. In theory we could make an alternative component that when pre-rendered by Astro given the user+valname it would fetch code from Val Town and provide links to open it. Something like this:

```mdx
<ValCode val="@stevekrouse/foo" />
```

![Image](https://github.com/val-town/val-town-docs/assets/5722272/0432be5b-6ad7-44c3-b351-fb02f2483164)

**Comment by stevekrouse** [comment]
Ok cool let's just do titles for everything, but without the file extension ie `.tsx`

Yeah I like that idea for existing vals, but maybe down the line
