### ISSUE TITLE
Mark custom domains as a "Pro" feature

### ISSUE THREAD

**Issue by Xkonti** [val-town/val-town-docs#86]
- The content of the docs page should start with a disclaimer that it's a feature restricted only to Pro subscribers.
- The name of the page in the pages list could include some kind of `PRO` tag next to it.

![image](https://github.com/val-town/val-town-docs/assets/5722272/aa4d4ce3-107e-4abb-a73d-c20b29dda753)

**Comment by stevekrouse** [comment]
Great ticket!

**Comment by stevekrouse** [comment]
Moved to "Now" in the github project to indicate you can start implementing it whenever you want
