### ISSUE TITLE
Stumbled on a 404: old Discord bot link

### ISSUE THREAD

**Issue by case** [val-town/val-town-docs#94]
Per our [Twitter thread](https://x.com/stevekrouse/status/1743974942184518099), I noticed that this is returning a `404`:

`https://docs.val.town/discord-bot-that-replies-to-slash-commands`

**Comment by stevekrouse** [comment]
Thanks!

**Comment by stevekrouse** [comment]
Closed https://github.com/val-town/val-town-docs/pull/236
